apiVersion: v1
kind: Service
metadata:
  name: healthcare5-service
spec:
  selector:
    app: healthcare5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
